variables:
  system.debug: 'true'
  connexion_service_id_sast: 'CxSAST'
  
steps:
- task: checkmarx.cxsast.cx-scan-task.Application security testing@2023
  displayName: 'Application security testing'
  inputs:
    projectName: 'Azure'
    syncMode: true
    enableProxy: false
    enableSastScan: true
    CheckmarxService: '${{ variables.connexion_service_id_sast }}'
    sastProxyUrl: 
    preset: High and Medium
    customPreset: 
    engineConfigId: 
    fullTeamName: CxServer
    sastCaChainFilePath: ''
    overrideProjectSettings: false
    incScan: false
    fullScansScheduled: true
    fullScanCycle: 2
    forceScan: true
    folderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules'
    fileExtension: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules'
    projectCustomTags:
    scanCustomTags: 
    scaScanTimeout:
    scanTimeout: 5
    projectcustomfields: 
    customfields: 
    denyProject: false
    comment: 'Sample YAML File'
    postScanAction: 
    generatePDFReport: true
    vulnerabilityThreshold: false
    failBuildForNewVulnerabilitiesEnabled: false
    failBuildForNewVulnerabilitiesSeverity: 
    high: 
    medium: 
    low: 
    enablePolicyViolations: false
    avoidDuplicateScans: false
    enableDependencyScan: false
    dependencyServerURL: 
    scaProxyUrl: 
    dependencyFileExtension: 
    dependencyFolderExclusion: 
    scaTeam: 
    scaCaChainFilePath: 
    scaConfigFilePaths: 
    scaEnvVariables: 
    isEnableScaResolver: 
    scaResolverAddParameters: 
    includeSource: 
    scaExploitablePath: 
    CheckmarxServiceForSca: 
    scaProjectFullPath: 
    scaProjectId:
    scaEnablePolicyViolations: 
    scaVulnerabilityThreshold: 
    scaHigh: 
    scaMedium: 
    scaLow:
